version: "3.9"
services:
  praktomat:
    build: praktomat
    ports:
      - 8000:8000
    volumes:
      - workdata:/home/praktomat/work-data
    depends_on:
      - postgresql
  postgresql:
    build: postgresql
    environment:
      POSTGRES_PASSWORD: superuser_password
volumes:
  workdata:
