version: "3.9"
services:
  praktomat:
    build:
      context: praktomat
      args:
        ID: ${COMPOSE_PROJECT_NAME}
        NAME: ${SITE_NAME}
        ADMIN: ${SERVER_ADMIN}
        DOMAIN: ${DOMAIN}
    volumes:
      - workdata:/home/praktomat/work-data
    depends_on:
      - postgresql
    networks:
      - database
      - praktomat
    labels:
      - traefik.enable=true
      - traefik.http.routers.praktomat-${COMPOSE_PROJECT_NAME}.rule=PathPrefix(`/${COMPOSE_PROJECT_NAME}`)
      - traefik.http.routers.praktomat-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
  postgresql:
    build: 
      context: postgresql
      args:
        ID: ${COMPOSE_PROJECT_NAME}
    environment:
      POSTGRES_PASSWORD: superuser_password
    networks:
      - database
volumes:
  workdata:
networks:
  database:
    name: ${COMPOSE_PROJECT_NAME}
  praktomat:
    external: true
