version: "3.9"
services:
  praktomat:
    container_name: ${COMPOSE_PROJECT_NAME}_praktomat
    image: praktomat
    volumes:
      - type: bind
        source: $HOME/work-data/$COMPOSE_PROJECT_NAME
        target: /home/praktomat/work-data
      - type: bind
        source: $PRAKTOMAT_EXTERNAL
        target: /home/praktomat/external
    depends_on:
      - postgresql
    networks:
      - database
      - praktomat
    labels:
      - traefik.enable=true
      - traefik.http.routers.praktomat-${COMPOSE_PROJECT_NAME}.rule=PathPrefix(`/${COMPOSE_PROJECT_NAME}`)
      - traefik.http.routers.praktomat-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.praktomat-${COMPOSE_PROJECT_NAME}.tls=true
    environment:
      - COMPOSE_PROJECT_NAME
      - PRAKTOMAT_NAME
      - PRAKTOMAT_ADMIN
      - PRAKTOMAT_DOMAIN
  postgresql:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:14.2-alpine
    volumes:
      - type: bind
        source: $PWD/postgresql/init.sh
        target: /docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_PASSWORD=superuser_password
      - COMPOSE_PROJECT_NAME
    networks:
      - database
networks:
  database:
    name: ${COMPOSE_PROJECT_NAME}
  praktomat:
    external: true
