version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    ports:
      - 443:443
    networks:
      - praktomat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: $PWD/traefik.toml
        target: /traefik.toml
      - type: bind
        source: $PWD/traefik_dynamic.toml
        target: /traefik_dynamic.toml
      - type: bind
        source: $PWD/cert.pem
        target: /cert.pem
      - type: bind
        source: $PWD/key.pem
        target: /key.pem
networks:
  praktomat:
    external: true
