services:
  traefik:
    image: traefik:v3.6.10
    ports:
      - 443:443
    networks:
      - praktomat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
      - $PWD/certbot:/certbot
  overview-page:
    image: kimchi
    build:
      context: ./kimchi
      dockerfile: Dockerfile
    networks:
      - praktomat
    volumes:
      - $PWD/overview-page/output:/page
    labels:
      - traefik.enable=true
      - traefik.http.routers.overview-page.rule=PathPrefix(`/`)
      - traefik.http.routers.overview-page.entrypoints=websecure
      - traefik.http.routers.overview-page.tls=true
  certbot:
    image: certbot/certbot:latest
    command: "true"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
networks:
  praktomat:
    external: true
