version: "3.9"
services:
  traefik:
    image: traefik:v2.10.4
    ports:
      - 443:443
    networks:
      - praktomat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
      - $PWD/cert.pem:/cert.pem
      - $PWD/key.pem:/key.pem
networks:
  praktomat:
    external: true
